spring.application.name=moviesSpringBoot

# Si la variable de entorno DB_URL existe, la usa. Si no, usa localhost.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mi_base_de_datos}

# Credenciales leídas obligatoriamente desde el entorno
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Driver y Dialecto
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Estrategia DDL
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}